# Generated by Django 4.1.11 on 2023-10-04 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('file', models.FileField(upload_to='upload/', verbose_name='文件')),
                ('base_station_num', models.IntegerField(verbose_name='基站数量')),
                ('step', models.IntegerField(verbose_name='步长')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RSS拟合历史记录',
                'verbose_name_plural': 'RSS拟合历史记录',
                'ordering': ['-created_time'],
            },
        ),
    ]
