# Generated by Django 4.1.11 on 2023-10-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssrecord',
            name='model_name',
            field=models.CharField(default='', max_length=50, verbose_name='模型'),
        ),
    ]
