# Generated by Django 4.1.11 on 2023-10-04 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0002_rssrecord_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssrecord',
            name='file',
            field=models.FileField(upload_to='upload/model_result/', verbose_name='文件'),
        ),
        migrations.CreateModel(
            name='RSSMatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('file', models.FileField(upload_to='upload/match_result/', verbose_name='文件')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('test_file', models.FileField(upload_to='upload/test_file/', verbose_name='测试文件')),
                ('db_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.rssrecord', verbose_name='RSS指纹数据库')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RSS指纹匹配',
                'verbose_name_plural': 'RSS指纹匹配',
                'ordering': ['-created_time'],
            },
        ),
    ]
