"""
Django settings for manageSystem project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-)tasfadsfdcsdvdsvdqx-71dil_sdsaddasa%q^bu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', ]

# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "system",
    "import_export",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "onlineClac.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "onlineClac.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "system",
        "HOST": "127.0.0.1",
        "PORT": "3306",
        "USER": "django",
        "PASSWORD": "password",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'upload'),
]

# 设置下载文件目录
MEDIA_URL = '/download/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload/')
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_DEFAULT_THEME = 'layui.css'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST = 'yoursmtpserver'
# EMAIL_HOST = "smtp-mail.outlook.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = 'youremail'
EMAIL_HOST_PASSWORD = 'pwd'
EMAIL_FROM = 'email'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = '/'

SIMPLEUI_LOGO = 'https://gitee.com/ijustyce/vue-element-admin-electron/raw/master/pack/electron/icons/icon.png'

# SIMPLEUI_ICON = {
#     '厂商': 'fas fa-kaaba',
#     '登记入库': 'fas fa-plus',
# }

# 设置导航栏
SIMPLEUI_CONFIG = {
    'system_keep': False,
    'menus': [
        {
            'name': '系统管理',
            'icon': 'fas fa-shield-alt',
            'models': [
                {
                    'name': '用户管理',
                    'icon': 'fas fa-user',
                    'url': '/admin/auth/user/',
                },
                {
                    'name': '组管理',
                    'icon': 'fas fa-users-cog',
                    'url': '/admin/auth/group/',
                }
            ]
        },
        {
            'name': '拟合管理',
            'icon': 'fab fa-microsoft',
            'models': [
                {
                    'name': 'RSS指纹库生成',
                    'icon': 'fas fa-code-branch',
                    'url': '/view/upload/',
                },
                {
                    'name': 'RSS指纹库生成历史',
                    'icon': 'fas fa-code-branch',
                    'url': '/admin/system/rssrecord/',
                },
                {
                    'name': 'RSS指纹匹配',
                    'icon': 'fas fa-code-branch',
                    'url': '/admin/system/rssmatchdata/',
                },
                {
                    'name': 'RSS指纹匹配效果图',
                    'icon': 'fas fa-code-branch',
                    'url': '/view/show_charts/',
                }
            ]
        }
    ]
}

IMPORT_EXPORT_USE_TRANSACTIONS = True

# SIMPLEUI_HOME_PAGE = '/view/upload/'
SIMPLEUI_HOME_TITLE = '概览'
SIMPLEUI_HOME_ICON = 'fa fa-eye'